Fix potential IndexOutOfBoundsException in curActorIsBlocking and concurrentActorCausesBlocking
JetBrains/lincheck pull request #277
Opened 2024-02-20 00:09 UTC by eupp

both properties access the current actor id `actorId = currentActorId[iThread]` but do not handle the case when `actorId = -1`, that is the case before any actor has started executing

2024-02-21 15:08 UTC, eupp commented
@ndkoval I've looked into this, and it seems it would be hard to trigger the error and make such test deterministic.
For this problem to occur, it has to be the case, that one thread has started working and detected deadlock, while other threads has not yet started execution (i.e. did not call `onActorStart` for the first time). We have no control over threads execution order on this level. 

One possible way to write test would be to manually create `ModelCheckingStrategy` instance and call its methods in specific order to trigger the error. Do you think we should take this road?

2024-02-21 19:58 UTC, ndkoval commented
@eupp, in this case, I would suggest adding a comment describing why the added logic is required and leaving a link to this PR.

2024-02-21 19:59 UTC, ndkoval commented
Maybe it would be better to rewrite the code in a way similar to

```
// <comment describing the issue>
if (actorId < 0) return null
```

2024-02-22 12:43 UTC, ndkoval approved these changes

2024-02-22 12:45 UTC, ndkoval requested changes
Please fix the build failure on Java 17 (Mac).

2024-02-27 11:06 UTC, ndkoval approved these changes

2024-02-27 11:07 UTC, merged