Object numeration mismatch fix
JetBrains/lincheck pull request #344
Opened 2024-07-22 13:43 UTC by avpotapov00

closes #343

2024-08-29 10:50 UTC, ndkoval requested changes
Hi @avpotapov00! I've reviewed the PR and left some comments. Could you please also rebase it onto the current `develop`?

2024-08-29 10:50 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
> +            invokeStatic(Injections::enumerateObjectsIfNeeded)
This logic contradicts with the `invokeBeforeEvent` function name

2024-08-29 10:50 UTC, ndkoval commented on src/jvm/test/resources/expected_logs/obstruction_freedom_violation_events_cut.txt
> +|                                                                                                                     |   q.enqueue(-1) at ObstructionFreedomViolationEventsCutTest.enqueue(SpinlockEve
Is there any difference besides the line numbers? Please check other outputs as well.

2024-09-24 16:30 UTC, ndkoval commented
@avpotapov00 could you please rebase the PR onto `develop` and address the comments?

2025-06-30 12:35 UTC, ndkoval commented
@eupp should we close this PR without merging it?

2025-06-30 18:54 UTC, eupp commented
> should we close this PR without merging it?

Yes, the whole approach to object numeration was rethought in https://github.com/JetBrains/lincheck/pull/702

2025-06-30 18:54 UTC, closed without merging