Multiple suspension points support
JetBrains/lincheck pull request #348
Opened 2024-07-28 22:56 UTC by avpotapov00

Closes #347

2024-08-16 18:13 UTC, eupp commented
We discussed this PR today with @avpotapov00 , and come to the conclusion that it overlaps with #361. 

This PR implements three things:
1. Fix for events tracking in a resumption part of a coroutine.
2. Fix for the trace collection in a resumption part of a coroutine. 
3. Multiple suspension points support. 

Independently, while working on the new model checking strategy, I also discovered problems (1) and (2), and opened PR #361.

At first I was only aware that this PR fixes (1), so I borrowed the relevant code in the commit [ab760ef](https://github.com/JetBrains/lincheck/pull/361/commits/ab760efd7b3a52579d8f95caebd110b3e44dcc46). 

Then I independently developed different fix for (2). 
As we discussed today, this fix also handles more complicated case, when the resumed part of the coroutine has several nested `suspend` functions.  To handle this case, I save the stack of suspended functions, and then restore it on resumption. 

So after the discussion, we thought that it would be good idea to split this PR into two parts. 

1. The first part should contain fixes for problems (1) and (2), and will be delivered under #361 
2. The second part should contain the multiple suspension points logic, and should be delivered after the first part.

2024-12-26 20:45 UTC, eupp commented
@avpotapov00 @ndkoval I've rebased the PR on `develop`, please have a look.

2025-01-09 11:55 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt
>              runOutsideIgnoredSection(thread) {
Why should this code be called outside the ignored section?

2025-01-09 11:55 UTC, ndkoval requested changes

2025-01-09 11:55 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (guarantee == ManagedGuaranteeType.TREAT_AS_ATOMIC &&
Could you please add a comment explaining what is going on here?

2025-02-04 10:54 UTC, ndkoval approved these changes

2025-02-04 10:55 UTC, merged