Non-determinism fix: ClassLoaders are now transformed in the Model Checking mode.
JetBrains/lincheck pull request #413
Opened 2024-10-07 17:10 UTC by avpotapov00

closes #412, #377

2024-10-08 09:55 UTC, ndkoval requested changes
Hi, @avpotapov00, thanks for the fix!

Could you please add a simple test that reveals the bug and measure the performance impact of this change? Intuitively, when running a single test, re-instrumenting all classes with `ClassLoader` in their names can increase the running time by several seconds.

2024-10-14 12:06 UTC, avpotapov00 commented on src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/channel/BufferedChannelTest.kt
> +class BufferedChannelTest {
It's not a good decision to put the implementation into the current file, it becomes huge.

2024-10-15 18:43 UTC, ndkoval requested changes

2024-10-15 18:43 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
> +            !isClassLoader(internalClassName)) {
Please fix the indentation

2024-10-15 18:43 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/TransformationUtils.kt
> +internal fun isClassLoader(className: String): Boolean = className.contains("ClassLoader")
Please rename the function to indicate a possibility of false positives (or make it `isNotClassLoader` and add the comment about false positives where you use the function)

2024-10-15 18:43 UTC, ndkoval commented on src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/channel/BufferedChannelTest.kt
> +    Param(name = "elem", gen = IntGen::class, conf = "1:3"),
Do you need these parameters?

2024-10-15 18:43 UTC, ndkoval commented on src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/channel/BufferedChannelTest.kt
> +class BufferedChannelTest {
It's huge anyway, but this is just a copy-and-paste from somewhere (which should be indicated)

2024-10-17 17:05 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
> +            !containsClassloaderInName(internalClassName)) {
Should it be `!containsClassloaderInName` or `containsClassloaderInName` here?

2024-10-17 17:07 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt
> +            !containsClassloaderInName(internalClassName)) {
Please add a comment that we always transform class loaders

2024-10-17 17:08 UTC, ndkoval commented on src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/channel/IncorrectBufferedChannel.kt
> + * Incorrect implementation of the BufferedChannel, intentionally provided by Daria Shutina.
Please add a reference to the issue, and put the code and the test in the same file.

2024-10-17 22:36 UTC, ndkoval approved these changes

2024-10-17 22:36 UTC, merged