Remove atomic setter transformers
JetBrains/lincheck pull request #428
Opened 2024-11-27 18:33 UTC by eupp

Remove separate bytecode transformers which tracked methods like `.set`, `.compareAndSet`, etc, of `VarHandle`, `AFU`, and `Unsafe` APIs, to inform the `ObjectTracker` about changes in object graph topology (`registerObjectLink` listener). 

Instead, modify `ManagedStrategy::beforeMethodCall` to parse the method name and arguments to extract relevant information and pass it into `ObjectTracker`. 

Also, it looks like the new approach is more robust and handles more cases, which were not handled previously (e.g. atomic array APIs). As such, there are changes in some `representation` tests --- the reported traces now include more events, which were previously incorrectly classified as local object accesses.

2024-11-28 09:04 UTC, ndkoval commented
@eupp, do we have tests checking that the local object detection works correctly with updates via methods like `.set`, `.compareAndSet`, etc, of `VarHandle`, `AFU`, and `Unsafe` APIs

2024-12-10 17:27 UTC, eupp commented
> @eupp, do we have tests checking that the local object detection works correctly with updates via methods like .set, .compareAndSet, etc, of VarHandle, AFU, and Unsafe APIs

Apparently, there are tests for AFU, Unsafe, and VarHandle APIs, but it looks like there are no tests for Atomics and Atomic Arrays. I can add them. 

https://github.com/JetBrains/lincheck/blob/c4745c88a8cb5a37bed6a2af6206ed099abf42af/src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/LocalObjectsTests.kt#L139

https://github.com/JetBrains/lincheck/blob/c4745c88a8cb5a37bed6a2af6206ed099abf42af/src/jvm/test/org/jetbrains/kotlinx/lincheck_test/transformation/LocalObjectsTests.kt#L231

https://github.com/JetBrains/lincheck/blob/c4745c88a8cb5a37bed6a2af6206ed099abf42af/src/jvm/test-jdk11/org/jetbrains/kotlinx/lincheck_test/transformation/VarHandleLocalObjectsTest.kt#L29

2024-12-24 18:14 UTC, eupp commented
I have added new tests to check that local object detection works correctly with `AtomicReference` and `AtomicReferenceArray` classes. Tests for other APIs (AFU, VarHandle, Unsafe) were already there.

2025-01-06 13:28 UTC, ndkoval requested changes

2025-01-06 13:28 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (atomicMethodDescriptor != null && atomicMethodDescriptor.kind.isSetter) {
Should the `isCasSetter` case also be covered here?

2025-01-06 13:28 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (atomicMethodDescriptor != null && atomicMethodDescriptor.kind.isSetter) {
This code becomes more and more complicated. I would suggest splitting the logical blocks of this method with comments explaining what each of these logical blocks does.

2025-01-08 09:36 UTC, eupp commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (atomicMethodDescriptor != null && atomicMethodDescriptor.kind.isSetter) {
`isSetter` includes `isCasSetter`:

```kotlin
internal val AtomicMethodKind.isSetter get() = when (this) {
    SET,
    GET_AND_SET,
    COMPARE_AND_SET,
    WEAK_COMPARE_AND_SET,
    COMPARE_AND_EXCHANGE
         -> true
    else -> false
}

internal val AtomicMethodKind.isCasSetter get() = when (this) {
    COMPARE_AND_SET,
    WEAK_COMPARE_AND_SET,
    COMPARE_AND_EXCHANGE
         -> true
    else -> false
}
```

Would you prefer to split the two, so that `isSetter` covers only `SET` and `GET_AND_SET` ?

2025-01-08 09:36 UTC, eupp commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (atomicMethodDescriptor != null && atomicMethodDescriptor.kind.isSetter) {
Done

2025-01-08 11:22 UTC, ndkoval commented on src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt
> +            if (atomicMethodDescriptor != null && atomicMethodDescriptor.kind.isSetter) {
Got it, thanks. I think this is fine.

2025-01-08 11:23 UTC, ndkoval approved these changes

2025-01-08 11:23 UTC, merged